{"trial_id": "0191", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "activation", "default": "relu", "conditions": [], "values": ["relu", "sigmoid"], "ordered": false}}, {"class_name": "Int", "config": {"name": "layer_1", "default": null, "conditions": [], "min_value": 5, "max_value": 30, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "layer_2", "default": null, "conditions": [], "min_value": 5, "max_value": 30, "step": 1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.001, "conditions": [], "values": [0.001, 0.01, 0.1], "ordered": true}}], "values": {"activation": "relu", "layer_1": 27, "layer_2": 20, "learning_rate": 0.1, "tuner/epochs": 23, "tuner/initial_epoch": 8, "tuner/bracket": 3, "tuner/round": 1, "tuner/trial_id": "0148"}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 273, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 238, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/tensorflow/python/eager/execute.py\", line 53, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node Adam/truediv_3 defined at (most recent call last):\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/runpy.py\", line 87, in _run_code\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/spyder_kernels/console/__main__.py\", line 24, in <module>\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/spyder_kernels/console/start.py\", line 331, in main\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 701, in start\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 195, in start\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/asyncio/events.py\", line 80, in _run\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in dispatch_queue\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 523, in process_one\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 429, in dispatch_shell\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 767, in execute_request\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 429, in do_execute\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n\n  File \"/var/folders/wk/ppkwh92d4hb_1fqwtwsw63n80000gn/T/ipykernel_54673/3133738299.py\", line 1, in <module>\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/spyder_kernels/customize/spydercustomize.py\", line 528, in runfile\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/spyder_kernels/customize/spydercustomize.py\", line 615, in _exec_file\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/spyder_kernels/customize/spydercustomize.py\", line 473, in exec_code\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/spyder_kernels/py3compat.py\", line 356, in compat_exec\n\n  File \"/Users/francesco/Desktop/NeuralNetworks/02_full_daily_NN/2-hyperparameters_tuning/keras-tuner_model_selection.py\", line 91, in <module>\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 233, in search\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 273, in _try_run_and_update_trial\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 238, in _run_and_update_trial\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1807, in fit\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1401, in train_function\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1384, in step_function\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1373, in run_step\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1154, in train_step\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 544, in minimize\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1223, in apply_gradients\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 652, in apply_gradients\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1253, in _internal_apply_gradients\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1345, in _distributed_apply_gradients_fn\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 1342, in apply_grad_to_update_var\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py\", line 241, in _update_step\n\n  File \"/Users/francesco/miniconda3/envs/droughts/lib/python3.9/site-packages/keras/src/optimizers/adam.py\", line 204, in update_step\n\nIncompatible shapes: [27] vs. [0]\n\t [[{{node Adam/truediv_3}}]] [Op:__inference_train_function_1803000]\n"}